#!/usr/local/bin/bash
if [ $# = 0 ]; then
    echo ""
    echo "指定ディレクトリ以下にある全ファイル内の文字列を置換します。"
    echo "元ファイルは現在月日でバックアップします。(ex. file.txt.20051201)"
    echo ""
    echo "Usage: multirep path from to"
    echo "   Ex: multirep /tmp nakakuda@mail.yahoo.co.jp nakakuda@yahoo-corp.jp"
    exit 1
fi

dir=$1
from=$2
to=$3
date=`date "+%Y%m%d"`

for f in `find $dir -type f`; do
    perl -p -i.$date -e 's/$2/$3/g' $f
done
